apiVersion: v1
kind: Pod
metadata:
  name: hza-try
  namespace: ucsd-haosulab
  labels:
    user: hza
spec:
  containers:
  - name: gpu-container
    image: hzaskywalker/kissshot
    # imagePullPolicy: Always
    command:
    - "bash"
    args: ["-c", "/cephfs/hza/mp/kube_install.sh; sleep infinity"]
    resources:
      requests:
        cpu: "2"
        memory: "8Gi"
        nvidia.com/gpu: 0
      limits:
        cpu: "2"
        memory: "8Gi"
        nvidia.com/gpu: 0
    volumeMounts:
      - name: cephfs
        mountPath: /cephfs
      - name: dshm
        mountPath: /dev/shm
  volumes:
    - name: dshm  # shared memory
      emptyDir:
        medium: Memory
    - name: cephfs
      persistentVolumeClaim:
        claimName: haosulab-cephfs
  restartPolicy: Never


  tolerations:
  - effect: NoSchedule
    key: nautilus.io/haosu
    operator: Exists